=== tufener/Java/CGIworkspaceXML/tpXML_DTD1/WebContent/list.dtd
<!ELEMENT list (recipe+)>
<!ELEMENT recipe (author,recipe_name,meal,ingredients,directions)>
<!ELEMENT ingredients (item+)>
<!ELEMENT item EMPTY>
<!ELEMENT author (#PCDATA)>
<!ELEMENT recipe_name (#PCDATA)>
<!ELEMENT directions (#PCDATA)>
<!ELEMENT meal (#PCDATA|course)*>
<!ELEMENT course (#PCDATA)>
<!ATTLIST item quantity CDATA #IMPLIED>
<!ATTLIST item type CDATA #REQUIRED>
<!ATTLIST directions totaltime CDATA #REQUIRED>

=== tufener/Java/CGIworkspaceXML/tpXML_DTD1/WebContent/list.xml
<?xml version="1.0" ?>
<!DOCTYPE list SYSTEM "list.dtd">
<list>
    <recipe>
        <author>Carol Schmidt</author>
        <recipe_name>Chocolate Chip Bars</recipe_name>
        <meal>
            Dinner
            <course>Dessert</course>
        </meal>
        <ingredients>
            <item quantity="2/3 C" type="butter" />
            <item quantity="2 C" type="brown sugar" />
            <item quantity="1 tsp" type="vanilla" />
            <item quantity="1 3/4 C" type="unsifted all-purpose flour" />
            <item quantity="1 1/2 tsp" type="baking powder" />
            <item type="salt" />
            <item quantity="3" type="eggs" />
            <item quantity="1/2 C" type="chopped nuts" />
            <item quantity="2 cups (12-oz pkg.)" type="semi-sweet choc. chips" />
        </ingredients>
        <directions totaltime="50min">
            Preheat oven to 350 degrees. Melt butter; combine with brown sugar and vanilla in large mixing bowl.Set aside to cool. 
            Combine flour, baking powder, and salt; set aside. Add eggs to cooled sugar mixture; beat well. Stir in reserved dry ingredients, nuts, and chips. 
            Spread in greased 13-by-9-inch pan. Bake for 25 to 30 minutes until golden brown; cool. Cut into squares.
        </directions>
    </recipe>
</list>
